//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViajesTerrestres.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public Nullable<int> PasajeroRefId { get; set; }
        public Nullable<int> RutaRefId { get; set; }
        public Nullable<int> NumeroDeSilla { get; set; }
    
        public virtual Pasajero Pasajero { get; set; }
        public virtual Ruta Ruta { get; set; }
    }
}
